name: Deploy HOS Production

on:
  workflow_dispatch: # This allows the workflow to be manually triggered from the GitHub UI

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: hos-production

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud using OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{vars.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-identity-pool/providers/github
          service_account: ${{vars.GCP_SA_EMAIL}}

      - name: Configure gcloud
        run: gcloud config set project ${{vars.GCP_PROJECT_ID}}

      - name: Login to Artifact Registry
        run: gcloud auth configure-docker ${{vars.GCP_REGION}}-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t ${{vars.GCP_DOCKER_IMAGE}} .

      - name: Push Docker image to Artifact Registry
        run: docker push ${{vars.GCP_DOCKER_IMAGE}}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy near-api \
            --image ${{vars.GCP_DOCKER_IMAGE}} \
            --region ${{vars.GCP_REGION}}
