name: Deploy Prod

on:
  workflow_dispatch: # This allows the workflow to be manually triggered from the GitHub UI

env:
  PROJECT_NUMBER: "237405837378"
  SERVICE_ACCOUNT_EMAIL: "github-actions@agora-near-25q2.iam.gserviceaccount.com"
  PROJECT_ID: "agora-near-25q2"
  REGION: "us-west1"
  DOCKER_IMAGE: "us-west1-docker.pkg.dev/agora-near-25q2/near-api/near-api"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud using OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-identity-pool/providers/github
          service_account: ${{env.SERVICE_ACCOUNT_EMAIL}}

      - name: Configure gcloud
        run: gcloud config set project ${{env.PROJECT_ID}}

      - name: Login to Artifact Registry
        run: gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t ${{env.DOCKER_IMAGE}} .

      - name: Push Docker image to Artifact Registry
        run: docker push ${{env.DOCKER_IMAGE}}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy near-api \
            --image ${{env.DOCKER_IMAGE}} \
            --region ${{env.REGION}}
